/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Philosophy = {
  _id: string;
  _type: "philosophy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  aboutHeading?: string;
  aboutText?: string;
  aboutImage?: ImageWithAlt;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  decorative?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  author: string;
  role?: string;
  displayOrder?: number;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  location?: string;
  email?: string;
  phone?: string;
  instagramUrl?: string;
  copyrightText?: string;
  addressLines?: Array<string>;
  menuSlogan?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  buttonText?: string;
  brochure?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  autoReplySubject?: string;
  autoReplyGreeting?: string;
  autoReplyBody?: string;
  autoReplyClosing?: string;
  autoReplyResponseTime?: string;
  autoReplySignOffName?: string;
  autoReplySignOffCompany?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  items?: Array<string>;
  price?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  statement?: string;
  description?: string;
  heroImage?: ImageWithAlt;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  projectNumber?: string;
  slug: Slug;
  displayOrder?: number;
  tagline?: string;
  mainImage: ImageWithAlt;
  year?: string;
  location?: string;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Philosophy
  | SanityImageAssetReference
  | ImageWithAlt
  | Testimonial
  | Footer
  | SanityFileAssetReference
  | Contact
  | Service
  | Home
  | Project
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  _id,  title,  projectNumber,  "slug": slug.current,  tagline,  mainImage,  year,  location,  gallery,  description,  // Walks back through the run and wraps around to the newest from the  // oldest. The _id != ^._id guard on the fallback matters when only one  // project is published: without it the wrap-around resolves to the current  // project and "next project" links to the page you are already on.  "nextProject": coalesce(    *[_type == "project" && defined(slug.current) && _createdAt < ^._createdAt] | order(_createdAt desc)[0],    *[_type == "project" && defined(slug.current) && _id != ^._id] | order(_createdAt desc)[0]  ){ "slug": slug.current }}
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string;
  projectNumber: string | null;
  slug: string;
  tagline: string | null;
  mainImage: ImageWithAlt;
  year: string | null;
  location: string | null;
  gallery: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  nextProject: {
    slug: string;
  } | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]  | order(coalesce(displayOrder, 9999) asc, _createdAt desc){  _id,  title,  projectNumber,  "slug": slug.current,  mainImage}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  projectNumber: string | null;
  slug: string;
  mainImage: ImageWithAlt;
}>;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "home"][0]{  statement}
export type HOME_QUERY_RESULT = {
  statement: string | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "philosophy"][0]{  aboutHeading,  aboutText,  aboutImage}
export type ABOUT_QUERY_RESULT = {
  aboutHeading: string | null;
  aboutText: string | null;
  aboutImage: ImageWithAlt | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: CONTACT_QUERY
// Query: *[_type == "contact"][0]{  title,  intro,  buttonText}
export type CONTACT_QUERY_RESULT = {
  title: string | null;
  intro: string | null;
  buttonText: string | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: EMAIL_TEMPLATE_QUERY
// Query: *[_type == "contact"][0]{  "brochureUrl": brochure.asset->url,  autoReplySubject,  autoReplyGreeting,  autoReplyBody,  autoReplyClosing,  autoReplyResponseTime,  autoReplySignOffName,  autoReplySignOffCompany}
export type EMAIL_TEMPLATE_QUERY_RESULT = {
  brochureUrl: string | null;
  autoReplySubject: string | null;
  autoReplyGreeting: string | null;
  autoReplyBody: string | null;
  autoReplyClosing: string | null;
  autoReplyResponseTime: string | null;
  autoReplySignOffName: string | null;
  autoReplySignOffCompany: string | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: SITE_DETAILS_QUERY
// Query: *[_type == "footer"][0]{  email,  phone,  instagramUrl,  copyrightText,  addressLines,  menuSlogan}
export type SITE_DETAILS_QUERY_RESULT = {
  email: string | null;
  phone: string | null;
  instagramUrl: string | null;
  copyrightText: string | null;
  addressLines: Array<string> | null;
  menuSlogan: string | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"]  | order(coalesce(displayOrder, 9999) asc, _createdAt asc){  quote,  author,  role}
export type TESTIMONIALS_QUERY_RESULT = Array<{
  quote: string;
  author: string;
  role: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "project" && slug.current == $slug][0]{\n  _id,\n  title,\n  projectNumber,\n  "slug": slug.current,\n  tagline,\n  mainImage,\n  year,\n  location,\n  gallery,\n  description,\n  // Walks back through the run and wraps around to the newest from the\n  // oldest. The _id != ^._id guard on the fallback matters when only one\n  // project is published: without it the wrap-around resolves to the current\n  // project and "next project" links to the page you are already on.\n  "nextProject": coalesce(\n    *[_type == "project" && defined(slug.current) && _createdAt < ^._createdAt] | order(_createdAt desc)[0],\n    *[_type == "project" && defined(slug.current) && _id != ^._id] | order(_createdAt desc)[0]\n  ){ "slug": slug.current }\n}': PROJECT_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)]\n  | order(coalesce(displayOrder, 9999) asc, _createdAt desc){\n  _id,\n  title,\n  projectNumber,\n  "slug": slug.current,\n  mainImage\n}': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)].slug.current': PROJECT_SLUGS_QUERY_RESULT;
    '*[_type == "home"][0]{\n  statement\n}': HOME_QUERY_RESULT;
    '*[_type == "philosophy"][0]{\n  aboutHeading,\n  aboutText,\n  aboutImage\n}': ABOUT_QUERY_RESULT;
    '*[_type == "contact"][0]{\n  title,\n  intro,\n  buttonText\n}': CONTACT_QUERY_RESULT;
    '*[_type == "contact"][0]{\n  "brochureUrl": brochure.asset->url,\n  autoReplySubject,\n  autoReplyGreeting,\n  autoReplyBody,\n  autoReplyClosing,\n  autoReplyResponseTime,\n  autoReplySignOffName,\n  autoReplySignOffCompany\n}': EMAIL_TEMPLATE_QUERY_RESULT;
    '*[_type == "footer"][0]{\n  email,\n  phone,\n  instagramUrl,\n  copyrightText,\n  addressLines,\n  menuSlogan\n}': SITE_DETAILS_QUERY_RESULT;
    '*[_type == "testimonial"]\n  | order(coalesce(displayOrder, 9999) asc, _createdAt asc){\n  quote,\n  author,\n  role\n}': TESTIMONIALS_QUERY_RESULT;
  }
}
